# Generated by Django 3.1.2 on 2021-04-24 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('ADMIN', 'ADMIN'), ('HR', 'HR'), ('ACCOUNTS', 'ACCOUNTS'), ('SALES', 'SALES'), ('BUSINESS DEVELOPMENT', 'BUSINESS DEVELOPMENT'), ('SYSTEM ADMIN', 'SYSTEM ADMIN'), ('EVENT COORDINATION', 'EVENT COORDINATION'), ('CUSTOMER RELATION', 'CUSTOMER RELATION'), ('OPERATIONS', 'OPERATIONS'), ('PHOTOGRAPHY', 'PHOTOGRAPHY'), ('ALBUM DESIGNING', 'ALBUM DESIGNING'), ('CC', 'CC'), ('DATA MANAGEMENT', 'DATA MANAGEMENT'), ('CINEMATOGRAPHY', 'CINEMATOGRAPHY'), ('PHOTO RETOUCHING', 'PHOTO RETOUCHING'), ('DIRECTION', 'DIRECTION'), ('VIDEO EDITING', 'VIDEO EDITING'), ('VIDEOGRAPHY', 'VIDEOGRAPHY'), ('SOCIAL MEDIA', 'SOCIAL MEDIA'), ('GRAPHIC DESIGNING', 'GRAPHIC DESIGNING'), ('SUPPORT SERIVICE', 'SUPPORT SERIVICE'), ('PRODUCTION', 'PRODUCTION'), ('EVENT MANAGEMENT', 'EVENT MANAGEMENT'), ('DIGITAL MARKETING', 'DIGITAL MARKETING'), ('ADMIN & OPERATIONS', 'ADMIN & OPERATIONS'), ('COLOUR CORRECTION', 'COLOUR CORRECTION'), ('LEARNING & DEVELOPMENT', 'LEARNING & DEVELOPMENT')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=3, null=True)),
                ('product_type', models.CharField(choices=[('laptop', 'laptop'), ('charger', 'charger'), ('monitor', 'monitor'), ('keyboard', 'keyboard'), ('mouse', 'mouse'), ('cabinet', 'cabinet'), ('SMPS', 'SMPS'), ('graphic card', 'graphic card'), ('RAM', 'RAM'), ('HDD', 'HDD'), ('other', 'other')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('barcode', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IMPORTED', 'IMPORTED'), ('EXPORTED', 'EXPORTED'), ('HYDRABAD', 'HYDRABAD'), ('BANGLORE', 'BANGLORE'), ('CHENNAI', 'CHENNAI'), ('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('SURAT', 'SURAT'), ('GOA', 'GOA')], max_length=50)),
                ('added_on', models.DateField(default=datetime.date.today)),
                ('shipped_on', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(choices=[('IMPORTED', 'IMPORTED'), ('EXPORTED', 'EXPORTED'), ('HYDRABAD', 'HYDRABAD'), ('BANGLORE', 'BANGLORE'), ('CHENNAI', 'CHENNAI'), ('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('SURAT', 'SURAT'), ('GOA', 'GOA')], max_length=50)),
                ('to_location', models.CharField(choices=[('IMPORTED', 'IMPORTED'), ('EXPORTED', 'EXPORTED'), ('HYDRABAD', 'HYDRABAD'), ('BANGLORE', 'BANGLORE'), ('CHENNAI', 'CHENNAI'), ('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('SURAT', 'SURAT'), ('GOA', 'GOA')], max_length=50)),
                ('update_time', models.DateField(default=datetime.date.today)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productunit')),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=models.SET('DELETED'), related_name='fromHolder', to='inventory.employee')),
                ('to_holder', models.ForeignKey(blank=True, null=True, on_delete=models.SET('DELETED'), related_name='toHolder', to='inventory.employee')),
            ],
        ),
    ]
