# Generated by Django 3.1.2 on 2021-04-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='barcode',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
