# Generated by Django 3.2 on 2021-04-22 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='added_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='barcode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='update_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
